### PR TITLE
Update requests version

### PR DESCRIPTION
**Pull request by ttheune**

### CODE REVIEW

**Comment by ttheune** [comment]
Checked the requests usages, those have stayed the same.

**Comment by aren** [comment]
tested?

**Comment by ttheune** [comment]
I've tested the requests line to ensure it returns the data the same way, I've no idea how to test the agent end to end.

**Comment by ttheune** [comment]
Tested successfully ready to merge:
Sending Access-Request of id 167 to 127.0.0.1 port 1812
	User-Name = "test"
	User-Password = "XXXXXXXXX"
	NAS-IP-Address = 172.17.0.2
	NAS-Port = 1
	Message-Authenticator = 0x00000000000000000000000000000000
rad_recv: Access-Accept packet from host 127.0.0.1 port 1812, id=167, length=20

**Pull request merged**
